_wandb:
    value:
        cli_version: 0.21.0
        e:
            5r5l0w3eodsu6yhzx4np61wo3xszogyo:
                args:
                    - --model_name_or_path
                    - parler-tts/parler-tts-mini-v1
                    - --use_precomputed_vectors
                    - --vector_base_path
                    - ./
                    - --vae_loss_weight
                    - "0.5"
                    - --orthogonality_loss_weight
                    - "1.0"
                    - --save_to_disk
                    - ./tmp_dataset_audio_vector_expresso/
                    - --temporary_save_to_disk
                    - ./audio_code_tmp_vector_expresso/
                    - --feature_extractor_name
                    - ylacombe/dac_44khZ_8kbps
                    - --description_tokenizer_name
                    - google/flan-t5-large
                    - --prompt_tokenizer_name
                    - google/flan-t5-large
                    - --report_to
                    - wandb
                    - --wandb_project
                    - parler-tts-vector-training
                    - --wandb_run_name
                    - GPU-Vector-Training-Test
                    - --overwrite_output_dir
                    - --output_dir
                    - ./output_dir_vector_training_expresso
                    - --train_dataset_name
                    - morateng/CapTTS-SFT-expresso-cleaned
                    - --train_dataset_config_name
                    - default
                    - --train_split_name
                    - train
                    - --eval_dataset_name
                    - morateng/CapTTS-SFT-expresso-cleaned
                    - --eval_dataset_config_name
                    - default
                    - --eval_split_name
                    - train
                    - --target_audio_column_name
                    - audio_path
                    - --prompt_column_name
                    - text
                    - --rebuilt_caption_column_name
                    - rebuilt_caption
                    - --max_duration_in_seconds
                    - "30"
                    - --min_duration_in_seconds
                    - "2.0"
                    - --max_text_length
                    - "600"
                    - --id_column_name
                    - id
                    - --preprocessing_num_workers
                    - "8"
                    - --do_train
                    - --num_train_epochs
                    - "1"
                    - --gradient_accumulation_steps
                    - "4"
                    - --per_device_train_batch_size
                    - "2"
                    - --learning_rate
                    - "0.0001"
                    - --adam_beta1
                    - "0.9"
                    - --adam_beta2
                    - "0.99"
                    - --weight_decay
                    - "0.01"
                    - --lr_scheduler_type
                    - constant_with_warmup
                    - --warmup_steps
                    - "100"
                    - --logging_steps
                    - "10"
                    - --freeze_text_encoder
                    - --do_eval
                    - --predict_with_generate
                    - --include_inputs_for_metrics
                    - --evaluation_strategy
                    - steps
                    - --eval_steps
                    - "50"
                    - --save_steps
                    - "50"
                    - --per_device_eval_batch_size
                    - "2"
                    - --audio_encoder_per_device_batch_size
                    - "8"
                    - --dtype
                    - bfloat16
                    - --seed
                    - "456"
                    - --dataloader_num_workers
                    - "4"
                    - --attn_implementation
                    - eager
                    - --max_train_samples
                    - "500"
                    - --max_eval_samples
                    - "50"
                codePath: parler-tts/training/run_parler_tts_vector_training.py
                codePathLocal: training/run_parler_tts_vector_training.py
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "982820896768"
                        used: "256817750016"
                email: morateng@naver.com
                executable: /home/user/Code/EF-TTS/.venv/bin/python3
                git:
                    commit: 97324a359e188a8087803a67b1f0fee278811632
                    remote: https://github.com/morateng/EF-TTS.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 8960
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-86647843-83a7-4cbe-0b02-cb72d8f7ec6f
                host: user-B760M-DS3H
                memory:
                    total: "67177291776"
                os: Linux-6.13.0-061300-generic-x86_64-with-glibc2.39
                program: /home/user/Code/EF-TTS/parler-tts/./training/run_parler_tts_vector_training.py
                python: CPython 3.9.23
                root: /home/user/Code/EF-TTS/parler-tts
                startedAt: "2025-07-25T06:33:59.237622Z"
                writerId: 5r5l0w3eodsu6yhzx4np61wo3xszogyo
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 100
            "3":
                - 13
            "4": 3.9.23
            "5": 0.21.0
            "6": 4.46.1
            "12": 0.21.0
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.99
freeze_text_encoder:
    value: true
global_batch_size:
    value: 2
gradient_accumulation_steps:
    value: 4
learning_rate:
    value: 0.0001
lr_scheduler_type:
    value: CONSTANT_WITH_WARMUP
max_duration_in_seconds:
    value: 30
mixed_precision:
    value: bf16
model_name_or_path:
    value: parler-tts/parler-tts-mini-v1
num_train_epochs:
    value: 1
per_device_train_batch_size:
    value: 2
temperature:
    value: 1
warmup_steps:
    value: 100
weight_decay:
    value: 0.01
